export { default as HomeHero } from './hero'
export { default as StatsBand } from './stats'
export { default as AboutSection } from './about-section'
export { default as BrandsSection } from './brands-section'

export { default as FeaturedProducts } from './featured-products'
export { default as WhyChoose } from './why-choose'
export { default as CtaBand } from './cta-band'
export { default as MainCategories } from './main-categories'
export { default as ServiceInstallation } from './service-installation'
export { default as WhatWeDo } from './what-we-do'
export { default as CustomerReviews } from './customer-reviews'
export { default as KeyFacts } from './key-facts'
export { default as ProjectsSection } from './projects-section'
